version: "3.1"
services:
  db:
    image: mongo:4.2
    container_name: data-amostra
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: amostra
      MONGO_INITDB_ROOT_USERNAME: usr_amostra
      MONGO_INITDB_ROOT_PASSWORD: usr_amostra